# Generated by Django 4.1.1 on 2023-07-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Product_type', models.CharField(max_length=255)),
                ('Experience', models.BooleanField(verbose_name=((True, 'Yes'), (False, 'No')))),
                ('Introduction', models.CharField(max_length=255)),
                ('Information', models.CharField(max_length=255)),
                ('GroupChat', models.BooleanField(verbose_name=((True, 'Yes'), (False, 'No')))),
                ('Questions', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
