# Generated by Django 4.1.1 on 2023-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_seller_first_name_seller_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Last_Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Questions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
