# Generated by Django 4.1.1 on 2023-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seller_last_name_alter_seller_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
